import { TrainingService } from "@/modules/training/services/training.service";
import * as TrainingTypes from "@/modules/training/types/training.types";

export const certMockData: TrainingTypes.TrainingCertificateRow[] = [
  {
    id: "cert-1",
    student: "Nguyễn Văn Tuấn",
    email: "tuan.nv@example.com",
    course: "React.js Mastery",
    className: "React.js K24",
    status: "COMPLETED",
    progress: 100,
    issuedAt: "2024-12-15T08:00:00Z",
  },
  {
    id: "cert-2",
    student: "Trần Mai Phương",
    email: "phuong.tm@example.com",
    course: "React.js Mastery",
    className: "React.js K24",
    status: "IN_PROGRESS" as any,
    progress: 85,
    issuedAt: null,
  },
  {
    id: "cert-3",
    student: "Lê Hoàng Vũ",
    email: "vu.lh@example.com",
    course: "IELTS Mastery",
    className: "IELTS 6.5 - Lớp Sáng",
    status: "DROPPED",
    progress: 30,
    issuedAt: null,
  },
  {
    id: "cert-4",
    student: "Phạm Thúy Vân",
    email: "van.pt@example.com",
    course: "Digital Marketing",
    className: "Marketing K12",
    status: "COMPLETED",
    progress: 100,
    issuedAt: "2024-11-20T08:00:00Z",
  },
  {
    id: "cert-5",
    student: "Đặng Nam Cường",
    email: "cuong.dn@example.com",
    course: "IELTS Mastery",
    className: "IELTS 8.0 - Lớp Tối",
    status: "ENROLLED" as any,
    progress: 0,
    issuedAt: null,
  },
];
