import type { ClassWorkspaceItem } from "./classes.types";

export const classMockData: ClassWorkspaceItem[] = [
  {
    id: "mock-class-1",
    name: "Digital Marketing Bootcamp",
    code: "OVC-DM-01",
    course: "Digital Marketing",
    instructor: "TRUNG MARKETING",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45).toISOString(),
    location: "Phòng đào tạo Ong Vàng",
    maxStudents: 30,
    students: 24,
    isActive: true,
    status: "opening",
    capacityRate: 80,
    risk: "Sắp đầy lớp",
    nextAction: "Chốt danh sách học viên còn thiếu học phí",
    activity: ["Tạo lịch học tuần này", "Cập nhật sĩ số 24/30", "Giảng viên xác nhận giáo án"],
  },
  {
    id: "mock-class-2",
    name: "AI for Marketing",
    code: "OVC-AI-02",
    course: "AI for Marketing",
    instructor: "Marketing OVC",
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    location: "Online Zoom",
    maxStudents: 25,
    students: 8,
    isActive: true,
    status: "upcoming",
    capacityRate: 32,
    risk: "Cần tuyển sinh thêm",
    nextAction: "Mở chiến dịch nhắc lead quan tâm AI",
    activity: ["Đã tạo lớp", "Chưa đủ sĩ số mục tiêu"],
  },
];
