import type { PotentialLeadView } from "./potential-students.types";

export const potentialStudentMockData: PotentialLeadView[] = [
  {
    id: "mock-lead-1",
    name: "Nguyen Minh Anh",
    email: "minhanh@example.com",
    phone: "0900000001",
    source: "Facebook Ads",
    interestedIn: "Digital Marketing",
    status: "new",
    note: "Muốn học buổi tối, cần tư vấn lộ trình.",
    nextFollowUpAt: new Date().toISOString(),
    score: 78,
    owner: "Marketing OVC",
    lastActivity: "Vừa nhận form đăng ký",
  },
  {
    id: "mock-lead-2",
    name: "Tran Thanh Tam",
    email: "thanhtam@example.com",
    phone: "0900000002",
    source: "Website",
    interestedIn: "Content Creator for Business",
    status: "scheduled",
    note: "Đã hẹn gọi lại để chốt lớp khai giảng gần nhất.",
    nextFollowUpAt: new Date(Date.now() + 86400000).toISOString(),
    score: 91,
    owner: "Tư vấn đào tạo",
    lastActivity: "Đã đặt lịch tư vấn",
  },
  {
    id: "mock-lead-3",
    name: "Le Hoang Gia",
    email: "hoanggia@example.com",
    phone: "0900000003",
    source: "Referral",
    interestedIn: "AI for Marketing",
    status: "contacted",
    note: "Quan tâm học cùng đội marketing nội bộ.",
    nextFollowUpAt: null,
    score: 64,
    owner: "Marketing OVC",
    lastActivity: "Đã nhắn Zalo",
  },
];
