import { TrainingService } from "@/modules/training/services/training.service";
import * as TrainingTypes from "@/modules/training/types/training.types";

export const courseMockData: TrainingTypes.TrainingCourseRow[] = [
  {
    id: "crs-1",
    title: "AI & Machine Learning cơ bản",
    description: "Nắm vững nền tảng AI và Machine Learning từ con số 0",
    status: "PUBLISHED",
    level: "Cơ bản",
    price: 3500000,
    currency: "VND",
    duration: 40,
    instructor: "Nguyễn Văn A",
    classes: 3,
    enrollments: 120,
    publishedAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "crs-2",
    title: "Lập trình Web với Next.js 14",
    description: "Xây dựng ứng dụng web hiện đại với Next.js App Router",
    status: "PUBLISHED",
    level: "Nâng cao",
    price: 4200000,
    currency: "VND",
    duration: 60,
    instructor: "Trần Thị B",
    classes: 2,
    enrollments: 85,
    publishedAt: "2024-02-20T08:00:00Z",
  },
  {
    id: "crs-3",
    title: "Thiết kế UI/UX Thực chiến",
    description: "Quy trình thiết kế sản phẩm từ nghiên cứu đến Prototype",
    status: "DRAFT",
    level: "Trung cấp",
    price: 2800000,
    currency: "VND",
    duration: 30,
    instructor: "Lê Hoàng C",
    classes: 0,
    enrollments: 0,
    publishedAt: null,
  },
  {
    id: "crs-4",
    title: "Phân tích dữ liệu với Python",
    description: "Xử lý và trực quan hóa dữ liệu với Pandas, Matplotlib",
    status: "PUBLISHED",
    level: "Cơ bản",
    price: 3200000,
    currency: "VND",
    duration: 45,
    instructor: "Phạm Đại D",
    classes: 5,
    enrollments: 210,
    publishedAt: "2023-11-10T08:00:00Z",
  },
  {
    id: "crs-5",
    title: "Marketing Automation",
    description: "Tự động hóa quy trình Marketing, tăng tỷ lệ chuyển đổi",
    status: "ARCHIVED",
    level: "Nâng cao",
    price: 5500000,
    currency: "VND",
    duration: 50,
    instructor: "Hoàng Minh E",
    classes: 1,
    enrollments: 45,
    publishedAt: "2023-06-01T08:00:00Z",
  },
  {
    id: "crs-6",
    title: "Tiếng Anh Giao tiếp Công sở",
    description: "Làm chủ tiếng Anh trong môi trường doanh nghiệp quốc tế",
    status: "PUBLISHED",
    level: "Mọi cấp độ",
    price: 2000000,
    currency: "VND",
    duration: 24,
    instructor: "Anna Nguyễn",
    classes: 8,
    enrollments: 350,
    publishedAt: "2024-03-05T08:00:00Z",
  },
];
