export const PERMISSIONS = {
  // CRM
  CRM_READ: "crm.read",
  CRM_CREATE: "crm.create",
  CRM_UPDATE: "crm.update",
  CRM_DELETE: "crm.delete",

  // Financial
  FINANCIAL_READ: "financial.read",
  FINANCIAL_CREATE: "financial.create",
  FINANCIAL_UPDATE: "financial.update",
  FINANCIAL_DELETE: "financial.delete",

  // Education (Admin/Manager scope)
  EDUCATION_READ: "education.read",
  EDUCATION_CREATE: "education.create",
  EDUCATION_UPDATE: "education.update",
  EDUCATION_DELETE: "education.delete",

  SOCIAL_MARKETING_READ: "social_marketing.read",
  SOCIAL_MARKETING_REPORT_READ: "social_marketing.report.read",
  SOCIAL_MARKETING_REPORT_SYNC: "social_marketing.report.sync",
  SOCIAL_MARKETING_REPORT_EXPORT: "social_marketing.report.export",
  SOCIAL_MARKETING_SETTINGS_UPDATE: "social_marketing.settings.update",
  SOCIAL_MARKETING_FACEBOOK_CONNECT: "social_marketing.facebook.connect",
  SOCIAL_MARKETING_FACEBOOK_DISCONNECT: "social_marketing.facebook.disconnect",
  SOCIAL_MARKETING_FACEBOOK_SYNC: "social_marketing.facebook.sync",

  // Notifications
  NOTIFICATION_READ: "notification.read",
  NOTIFICATION_CREATE: "notification.create",
  NOTIFICATION_UPDATE: "notification.update",
  NOTIFICATION_DELETE: "notification.delete",

  // Settings
  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",

  // Users & Roles
  USER_MANAGEMENT: "users.management",

  // Customer Portal Specific
  CUSTOMER_PORTAL_ACCESS: "portal.customer",

  PROJECTS_READ: "projects.read",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_UPDATE: "projects.update",
  PROJECTS_DELETE: "projects.delete",
  PROJECTS_MANAGE_MEMBERS: "projects.manage_members",
  PROJECTS_MANAGE_TASKS: "projects.manage_tasks",
  PROJECTS_MANAGE_FILES: "projects.manage_files",
  PROJECTS_MANAGE_DATABASE: "projects.manage_database",
  PROJECTS_SHARE_PUBLIC: "projects.share_public",
  PROJECTS_GUEST_EDIT: "projects.guest_edit",
  PROJECTS_MANAGE_SETTINGS: "projects.manage_settings",
  
  // Instructor Portal Specific
  INSTRUCTOR_PORTAL_ACCESS: "portal.instructor",
  
  // Student Portal Specific
  STUDENT_PORTAL_ACCESS: "portal.student",

  // Super Admin Specific
  SYSTEM_MANAGEMENT: "system.management",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Mapping roles to their default permissions
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.SYSTEM_MANAGEMENT,
    // Super Admin có mọi quyền, nhưng cơ bản chỉ cần SYSTEM_MANAGEMENT là bypass mọi thứ
  ],
  ADMIN: [
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_UPDATE, PERMISSIONS.CRM_DELETE,
    PERMISSIONS.FINANCIAL_READ, PERMISSIONS.FINANCIAL_CREATE, PERMISSIONS.FINANCIAL_UPDATE, PERMISSIONS.FINANCIAL_DELETE,
    PERMISSIONS.EDUCATION_READ, PERMISSIONS.EDUCATION_CREATE, PERMISSIONS.EDUCATION_UPDATE, PERMISSIONS.EDUCATION_DELETE,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.NOTIFICATION_CREATE, PERMISSIONS.NOTIFICATION_UPDATE, PERMISSIONS.NOTIFICATION_DELETE,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.PROJECTS_READ, PERMISSIONS.PROJECTS_CREATE, PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_DELETE, PERMISSIONS.PROJECTS_MANAGE_MEMBERS, PERMISSIONS.PROJECTS_MANAGE_TASKS,
    PERMISSIONS.PROJECTS_MANAGE_FILES, PERMISSIONS.PROJECTS_MANAGE_DATABASE, PERMISSIONS.PROJECTS_SHARE_PUBLIC,
    PERMISSIONS.PROJECTS_GUEST_EDIT, PERMISSIONS.PROJECTS_MANAGE_SETTINGS,
    PERMISSIONS.SOCIAL_MARKETING_READ, PERMISSIONS.SOCIAL_MARKETING_REPORT_READ,
    PERMISSIONS.SOCIAL_MARKETING_REPORT_SYNC, PERMISSIONS.SOCIAL_MARKETING_REPORT_EXPORT,
    PERMISSIONS.SOCIAL_MARKETING_SETTINGS_UPDATE, PERMISSIONS.SOCIAL_MARKETING_FACEBOOK_CONNECT,
    PERMISSIONS.SOCIAL_MARKETING_FACEBOOK_DISCONNECT, PERMISSIONS.SOCIAL_MARKETING_FACEBOOK_SYNC,
  ],
  MANAGER: [
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.FINANCIAL_READ, PERMISSIONS.FINANCIAL_CREATE, PERMISSIONS.FINANCIAL_UPDATE,
    PERMISSIONS.EDUCATION_READ, PERMISSIONS.EDUCATION_CREATE, PERMISSIONS.EDUCATION_UPDATE,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.NOTIFICATION_CREATE, PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.PROJECTS_READ, PERMISSIONS.PROJECTS_CREATE, PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_MANAGE_MEMBERS, PERMISSIONS.PROJECTS_MANAGE_TASKS,
    PERMISSIONS.PROJECTS_MANAGE_FILES, PERMISSIONS.PROJECTS_MANAGE_DATABASE, PERMISSIONS.PROJECTS_SHARE_PUBLIC,
    PERMISSIONS.SOCIAL_MARKETING_READ, PERMISSIONS.SOCIAL_MARKETING_REPORT_READ,
    PERMISSIONS.SOCIAL_MARKETING_REPORT_SYNC, PERMISSIONS.SOCIAL_MARKETING_FACEBOOK_SYNC,
    // Không cho MANAGER delete và settings (tùy config sau này)
  ],
  STAFF: [
    PERMISSIONS.CRM_READ, PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.FINANCIAL_READ,
    PERMISSIONS.EDUCATION_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.PROJECTS_READ, PERMISSIONS.PROJECTS_UPDATE, PERMISSIONS.PROJECTS_MANAGE_TASKS,
    PERMISSIONS.PROJECTS_MANAGE_FILES,
    PERMISSIONS.SOCIAL_MARKETING_READ, PERMISSIONS.SOCIAL_MARKETING_REPORT_READ,
  ],
  CUSTOMER: [
    PERMISSIONS.CUSTOMER_PORTAL_ACCESS,
  ],
  INSTRUCTOR: [
    PERMISSIONS.INSTRUCTOR_PORTAL_ACCESS,
  ],
  STUDENT: [
    PERMISSIONS.STUDENT_PORTAL_ACCESS,
  ],
};
