import type { OverviewClass, OverviewCourse, OverviewStudent, OverviewAlert, OverviewStat, TrainingOverviewData } from "./training-overview.types";

export const mockCourses: OverviewCourse[] = [
  {
    id: "course-1",
    title: "Digital Marketing Toàn diện",
    description: "Chiến lược, content, quảng cáo & đo lường hiệu quả marketing số từ A-Z.",
    instructor: "Nguyễn Minh Quân",
    instructorId: "inst-1",
    status: "PUBLISHED",
    level: "intermediate",
    classes: 3,
    enrollments: 42,
    price: 4500000,
    language: "vi",
    isPublic: true,
    isFeatured: true,
    activity: ["Vừa xuất bản", "42 học viên đăng ký", "3 lớp đang vận hành"],
  },
  {
    id: "course-2",
    title: "Facebook & TikTok Ads Nâng cao",
    description: "Target chuyên sâu, creative testing và tối ưu ROAS trên Meta & TikTok.",
    instructor: "Trần Thị Lan Anh",
    instructorId: "inst-2",
    status: "PUBLISHED",
    level: "advanced",
    classes: 2,
    enrollments: 28,
    price: 5800000,
    language: "vi",
    isPublic: true,
    isFeatured: false,
    activity: ["Khai giảng lớp B2 tuần tới", "28 học viên đăng ký"],
  },
  {
    id: "course-3",
    title: "SEO & Content Marketing",
    description: "Xây dựng traffic organic bền vững bằng content chất lượng và kỹ thuật SEO.",
    instructor: "Phạm Đức Huy",
    instructorId: "inst-3",
    status: "PUBLISHED",
    level: "beginner",
    classes: 1,
    enrollments: 19,
    price: 3200000,
    language: "vi",
    isPublic: true,
    isFeatured: false,
    activity: ["Lớp K1 đang diễn ra", "19 học viên đăng ký"],
  },
  {
    id: "course-4",
    title: "Google Analytics 4 & Ads",
    description: "Đo lường chuyển đổi, tối ưu chiến dịch và đọc dữ liệu GA4 thuần thục.",
    instructor: "Nguyễn Minh Quân",
    instructorId: "inst-1",
    status: "DRAFT",
    level: "intermediate",
    classes: 0,
    enrollments: 0,
    price: 3900000,
    language: "vi",
    isPublic: false,
    isFeatured: false,
    activity: ["Đang soạn nội dung", "Chưa có lớp vận hành"],
  },
  {
    id: "course-5",
    title: "Email Marketing & Automation",
    description: "Thiết kế chuỗi email, phân khúc list và tự động hóa nurturing campaign.",
    instructor: "Trần Thị Lan Anh",
    instructorId: "inst-2",
    status: "DRAFT",
    level: "beginner",
    classes: 0,
    enrollments: 0,
    price: 2800000,
    language: "vi",
    isPublic: false,
    isFeatured: false,
    activity: ["Đang soạn nội dung"],
  },
  {
    id: "course-6",
    title: "Branding & Visual Identity",
    description: "Xây dựng thương hiệu nhất quán từ logo, màu sắc đến giọng nói thương hiệu.",
    instructor: "Lê Hoàng Nam",
    instructorId: "inst-4",
    status: "ARCHIVED",
    level: "intermediate",
    classes: 2,
    enrollments: 35,
    price: 4200000,
    language: "vi",
    isPublic: false,
    isFeatured: false,
    activity: ["Đã lưu trữ", "35 học viên đã hoàn thành"],
  },
  {
    id: "course-7",
    title: "Copywriting & Storytelling",
    description: "Viết content thuyết phục, xây dựng câu chuyện thương hiệu và tăng tỷ lệ chuyển đổi.",
    instructor: "Phạm Đức Huy",
    instructorId: "inst-3",
    status: "PUBLISHED",
    level: "beginner",
    classes: 1,
    enrollments: 15,
    price: 2500000,
    language: "vi",
    isPublic: true,
    isFeatured: false,
    activity: ["Khai giảng tuần này", "15 học viên đăng ký"],
  },
  {
    id: "course-8",
    title: "Marketing Strategy & Planning",
    description: "Xây dựng chiến lược marketing dài hạn, phân bổ ngân sách và KPI tracking.",
    instructor: "Lê Hoàng Nam",
    instructorId: "inst-4",
    status: "PUBLISHED",
    level: "advanced",
    classes: 1,
    enrollments: 22,
    price: 6500000,
    language: "vi",
    isPublic: true,
    isFeatured: true,
    activity: ["Vừa mở đăng ký", "22 học viên đăng ký"],
  },
];

export const mockClasses: OverviewClass[] = [
  {
    id: "class-1",
    name: "Digital Marketing K1-2026",
    code: "DM-K1-2026",
    course: "Digital Marketing Toàn diện",
    courseId: "course-1",
    instructor: "Nguyễn Minh Quân",
    startDate: "2026-01-15",
    endDate: "2026-04-15",
    location: "Phòng 201 - Tòa nhà OVC",
    maxStudents: 20,
    students: 18,
    isActive: true,
    status: "opening",
    capacityRate: 90,
    nextAction: "Theo dõi tiến độ tuần 12",
    activity: ["18/20 học viên", "Tuần 12/16", "Điểm danh hôm nay"],
  },
  {
    id: "class-2",
    name: "Facebook Ads B2-2026",
    code: "FBA-B2-2026",
    course: "Facebook & TikTok Ads Nâng cao",
    courseId: "course-2",
    instructor: "Trần Thị Lan Anh",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    location: "Online - Zoom",
    maxStudents: 15,
    students: 0,
    isActive: true,
    status: "upcoming",
    capacityRate: 0,
    nextAction: "Mở đăng ký và thông báo học viên",
    activity: ["Lớp sắp khai giảng", "Chưa có học viên đăng ký"],
  },
  {
    id: "class-3",
    name: "SEO Content K1-2026",
    code: "SEO-K1-2026",
    course: "SEO & Content Marketing",
    courseId: "course-3",
    instructor: "Phạm Đức Huy",
    startDate: "2026-03-01",
    endDate: "2026-06-01",
    location: "Phòng 305 - Tòa nhà OVC",
    maxStudents: 15,
    students: 15,
    isActive: true,
    status: "full",
    capacityRate: 100,
    nextAction: "Đóng đăng ký, chuẩn bị khai giảng",
    activity: ["Lớp đầy 15/15", "Danh sách chờ: 3 người"],
  },
  {
    id: "class-4",
    name: "Digital Marketing K2-2025",
    code: "DM-K2-2025",
    course: "Digital Marketing Toàn diện",
    courseId: "course-1",
    instructor: "Nguyễn Minh Quân",
    startDate: "2025-07-01",
    endDate: "2025-10-31",
    location: "Phòng 201 - Tòa nhà OVC",
    maxStudents: 20,
    students: 20,
    isActive: false,
    status: "closed",
    capacityRate: 100,
    nextAction: "Cấp chứng chỉ cho học viên hoàn thành",
    activity: ["Lớp đã kết thúc", "17/20 hoàn thành", "Cấp chứng chỉ đang xử lý"],
  },
  {
    id: "class-5",
    name: "Copywriting K1-2026",
    code: "COPY-K1-2026",
    course: "Copywriting & Storytelling",
    courseId: "course-7",
    instructor: "Phạm Đức Huy",
    startDate: "2026-06-28",
    endDate: "2026-08-28",
    location: "Online - Google Meet",
    maxStudents: 12,
    students: 8,
    isActive: true,
    status: "opening",
    capacityRate: 67,
    nextAction: "Gửi tài liệu buổi 1",
    activity: ["8/12 học viên", "Buổi 1 sắp diễn ra"],
  },
  {
    id: "class-6",
    name: "Marketing Strategy K1-2026",
    code: "MS-K1-2026",
    course: "Marketing Strategy & Planning",
    courseId: "course-8",
    instructor: "Lê Hoàng Nam",
    startDate: "2026-07-15",
    endDate: "2026-10-15",
    location: "Phòng 401 - Tòa nhà OVC",
    maxStudents: 10,
    students: 3,
    isActive: true,
    status: "upcoming",
    capacityRate: 30,
    nextAction: "Tiếp tục tuyển sinh",
    activity: ["3/10 học viên đăng ký", "Còn 15 ngày khai giảng"],
  },
];

export const mockStudents: OverviewStudent[] = [
  {
    id: "stu-1",
    name: "Nguyễn Thị Thu Hà",
    email: "thuha@gmail.com",
    phone: "0901234567",
    enrollments: 3,
    active: 2,
    completed: 1,
    progress: 15,
    status: "risk",
    owner: "CSKH Đào tạo",
    nextAction: "Gọi nhắc lịch học và bài tập",
    note: "Học viên bỏ nhịp 2 buổi gần đây, cần can thiệp sớm.",
    activity: ["Vắng buổi 10 & 11", "Tiến độ 15%", "2 khóa đang học"],
  },
  {
    id: "stu-2",
    name: "Trần Văn Bình",
    email: "binh.tran@company.vn",
    phone: "0912345678",
    enrollments: 2,
    active: 2,
    completed: 0,
    progress: 68,
    status: "learning",
    owner: "Training OVC",
    nextAction: "Theo dõi tiến độ tuần này",
    note: "Học viên tích cực, hoàn thành bài tập đúng hạn.",
    activity: ["Tiến độ 68%", "Hoàn thành bài tập tuần 8", "2 khóa đang học"],
  },
  {
    id: "stu-3",
    name: "Phạm Thị Minh Châu",
    email: "chau.pham@gmail.com",
    phone: "0923456789",
    enrollments: 1,
    active: 1,
    completed: 0,
    progress: 45,
    status: "learning",
    owner: "Training OVC",
    nextAction: "Gửi tài liệu bổ sung tuần 6",
    note: "Tiến độ ổn định, cần hỗ trợ thêm về phần thực hành.",
    activity: ["Tiến độ 45%", "Hoàn thành bài tập tuần 5"],
  },
  {
    id: "stu-4",
    name: "Lê Quang Hải",
    email: "hai.le@startup.io",
    phone: "0934567890",
    enrollments: 1,
    active: 0,
    completed: 1,
    progress: 100,
    status: "completed",
    owner: "Training OVC",
    nextAction: "Chuẩn bị và cấp chứng chỉ",
    note: "Đã hoàn thành khóa học với điểm xuất sắc.",
    activity: ["Hoàn thành 100%", "Điểm tổng kết: 92/100", "Đủ điều kiện chứng chỉ"],
  },
  {
    id: "stu-5",
    name: "Võ Thị Kim Ngân",
    email: "ngan.vo@gmail.com",
    phone: "0945678901",
    enrollments: 0,
    active: 0,
    completed: 0,
    progress: 0,
    status: "new",
    owner: "Training OVC",
    nextAction: "Gán khóa học phù hợp",
    note: "Học viên mới chưa đăng ký khóa nào.",
    activity: ["Hồ sơ mới tạo", "Chưa đăng ký khóa học"],
  },
  {
    id: "stu-6",
    name: "Đỗ Hữu Nghĩa",
    email: "nghia.do@agency.vn",
    phone: "0956789012",
    enrollments: 2,
    active: 1,
    completed: 1,
    progress: 72,
    status: "learning",
    owner: "Training OVC",
    nextAction: "Check-in tiến độ cuối tháng",
    note: "Hoàn thành 1 khóa, đang học khóa 2.",
    activity: ["Tiến độ 72%", "1 khóa đã hoàn thành"],
  },
  {
    id: "stu-7",
    name: "Bùi Thị Thanh Thảo",
    email: "thao.bui@gmail.com",
    phone: "0967890123",
    enrollments: 1,
    active: 1,
    completed: 0,
    progress: 8,
    status: "risk",
    owner: "CSKH Đào tạo",
    nextAction: "Gọi hỏi thăm và hỗ trợ",
    note: "Tiến độ rất thấp, có nguy cơ bỏ học.",
    activity: ["Tiến độ chỉ 8%", "Vắng 3 buổi liên tiếp"],
  },
  {
    id: "stu-8",
    name: "Hoàng Minh Tuấn",
    email: "tuan.hoang@tech.com",
    phone: "0978901234",
    enrollments: 3,
    active: 0,
    completed: 3,
    progress: 100,
    status: "completed",
    owner: "Training OVC",
    nextAction: "Giới thiệu khóa học nâng cao",
    note: "Học viên xuất sắc, hoàn thành 3 khóa liên tiếp.",
    activity: ["3 khóa hoàn thành", "Chứng chỉ đã cấp", "Tiềm năng upsell cao"],
  },
];

export const mockAlerts: OverviewAlert[] = [
  {
    id: "alert-1",
    label: "3 học viên có tiến độ dưới 20% — cần can thiệp",
    href: "/workspace/training/students",
    tone: "red",
    icon: "AlertCircle",
  },
  {
    id: "alert-2",
    label: "5 học phí còn công nợ chưa thu",
    href: "/workspace/training/tuition",
    tone: "amber",
    icon: "CircleDollarSign",
  },
  {
    id: "alert-3",
    label: "2 khóa học chưa có lớp vận hành",
    href: "/workspace/courses",
    tone: "orange",
    icon: "BookOpen",
  },
  {
    id: "alert-4",
    label: "Lớp Facebook Ads B2 sắp khai giảng — chưa đủ học viên",
    href: "/workspace/training/classes",
    tone: "blue",
    icon: "CalendarClock",
  },
];

export const mockStats: OverviewStat[] = [
  { id: "stat-revenue", label: "Đã thu học phí", value: "₫278.500.000", note: "Theo ghi danh lớp học", tone: "text-emerald-600 bg-emerald-50", icon: "WalletCards" },
  { id: "stat-debt", label: "Công nợ học phí", value: "₫42.000.000", note: "Còn phải thu", tone: "text-red-600 bg-red-50", icon: "WalletCards" },
  { id: "stat-students", label: "Học viên", value: 8, note: "Đang quản lý", tone: "text-blue-600 bg-blue-50", icon: "Users" },
  { id: "stat-leads", label: "Tiềm năng", value: 12, note: "Cần chăm sóc", tone: "text-amber-600 bg-amber-50", icon: "Sparkles" },
  { id: "stat-courses", label: "Khóa học", value: 8, note: "Chương trình đào tạo", tone: "text-orange-600 bg-orange-50", icon: "BookOpen" },
  { id: "stat-classes", label: "Lớp đang mở", value: 3, note: "Đang diễn ra", tone: "text-violet-600 bg-violet-50", icon: "School" },
  { id: "stat-instructors", label: "Giảng viên", value: 4, note: "Đội ngũ giảng dạy", tone: "text-rose-600 bg-rose-50", icon: "UserCheck" },
  { id: "stat-certs", label: "Chứng chỉ", value: 14, note: "Đã đủ điều kiện", tone: "text-cyan-600 bg-cyan-50", icon: "Award" },
];

export const mockOverviewData: TrainingOverviewData = {
  courses: mockCourses,
  classes: mockClasses,
  students: mockStudents,
  alerts: mockAlerts,
  stats: mockStats,
};
